import type { Interview } from '../types';
import type { Locale } from './config';

export const INTERVIEW_UI: Record<Locale, {
    heading: string;
    introduction: string;
    by: string;
    continueReading: string;
    back: string;
    coverAlt: (title: string) => string;
    illustrationAlt: (index: number) => string;
}> = {
    es: {
        heading: 'Entrevistas',
        introduction: 'Conversaciones y diálogos en profundidad.',
        by: 'Por',
        continueReading: 'Seguir leyendo',
        back: 'Volver',
        coverAlt: (title) => `Portada de ${title}`,
        illustrationAlt: (index) => `Ilustración de la entrevista ${index}`,
    },
    fr: {
        heading: 'Entretiens',
        introduction: 'Conversations et dialogues approfondis.',
        by: 'Par',
        continueReading: 'Lire la suite',
        back: 'Retour aux entretiens',
        coverAlt: (title) => `Couverture de ${title}`,
        illustrationAlt: (index) => `Illustration de l’entretien ${index}`,
    },
};

const FR_INTERVIEW_METADATA: Record<string, Partial<Interview>> = {
    'entrevista-antonio-carvajal': {
        title: 'ENTRETIEN AVEC ANTONIO CARVAJAL',
        publication: 'Ficciones, Revista de Letras. 2e époque. nº 1. Printemps 1997. p. 4-11',
        date: '13 mars 1997',
        intro: 'Nous sommes à la Faculté de traduction de l’Université de Grenade, où Antonio Carvajal exerce son activité professionnelle comme professeur de théorie de la littérature. Aujourd’hui, 13 mars 1997, il nous reçoit aimablement et aménage son emploi du temps chargé pour nous consacrer quelques instants.',
    },
    'entrevista-juan-carlos-sunen': {
        title: 'ENTRETIEN AVEC JUAN CARLOS SUÑÉN',
        publication: 'Ficciones, Revista de Letras. 2e époque. nº 2. Été/Automne 1997. p. 58-63',
        date: 'Été/Automne 1997',
        intro: 'Onze heures du matin. Nous sommes au Círculo de Bellas Artes de Madrid, où Juan Carlos Suñén, auteur de nombreux livres et lauréat de tout autant de prix nationaux, me reçoit.',
    },
    'entrevista-juan-carlos-rodriguez': {
        title: 'ENTRETIEN AVEC JUAN CARLOS RODRIGUEZ, UN PHILOSOPHE CONTEMPORAIN',
        publication: 'Ficciones, Revista de Letras. 2e époque. nº 4. Automne/Hiver 1998. p. 37-44',
        date: 'Automne/Hiver 1998',
        intro: `Juan Carlos Rodríguez fut professeur titulaire de littérature à la Faculté de philosophie et lettres de l’Université de Grenade. Il se consacra exclusivement à l’enseignement ainsi qu’à la recherche théorique et critique. Il publia les ouvrages suivants : Teoría e Historia de la Producción Ideológica (Madrid, Akal, 1975. 2e éd. 1990) ; Melodrama y Populismo en la cultura latinoamericana (inclus dans Granada Tango, 1981) ; La Norma Literaria (Grenade, Diputación Provincial, 1984. 2e éd. 1994) ; Moratín o el arte nuevo de hacer teatro (Grenade, La General, 1991) ; Introducción al estudio de la Literatura Hispanoamericana (Akal, 1987, en collaboration avec Álvaro Salvador. 2e éd. 1994) ; La Poesía, la Música y el Silencio (de Mallarmé a Wittgenstein) (Renacimiento, Séville, 1994) ; Lorca y el Sentido (Un Inconsciente para una Historia) (Madrid, Akal, 1994) ; La Literatura del Pobre (Grenade, Comares, 1994).

Son livre Teoría e Historia de la Producción Ideológica fut traduit par l’Université de New York, où il donna au printemps 1998 un cours intitulé « La renovación del pensamiento marxista: Louis Althusser y Juan Carlos Rodríguez ». Au printemps 1999, il y donna un autre cours intitulé « Neomarxismo y Postmodernismo: Juan Carlos Rodríguez y Anthony Cascardi ».

Parmi les autres ouvrages qu’il avait publiés au moment de l’entretien figuraient Brecht y el poder de la Literatura (Comares, collection De guante blanco) et El escritor que compró su propio libro (Comares, collection De guante blanco).`,
    },
};

const FR_INTERVIEW_CONTENT: Record<string, Record<number, string>> = {
    'entrevista-antonio-carvajal': {
        1: 'Ficciones. À vos débuts, nous trouvons un livre, Tigres en el Jardín, publié en 1968 et dédié à Vicente Aleixandre. Quelle influence ses textes ont-ils exercée sur vous ?',
        2: 'A. Carvajal : De Vicente Aleixandre comme poète, peu ; comme personne, énormément, car heureusement l’amitié est entrée en jeu. J’ai connu V. Aleixandre en 1965 et cette rencontre fut pour moi un événement absolument fondamental. Mais lorsque je l’ai rencontré, ma voix poétique était déjà presque formée, pas encore tout à fait affirmée, mais presque. Dans Tigres en el jardín, son influence est minime. Je l’avais lu, mais pas avec la même intensité que d’autres poètes, et l’empreinte de l’œuvre d’Aleixandre est bien plus perceptible dans certains de mes livres ultérieurs.',
        3: 'F. : Et quels écrivains ont depuis lors influencé votre œuvre ?',
        5: 'A. C. : Dans Tigres en el Jardín, l’empreinte de Rubén Darío est très claire, et je ne sais pas pourquoi les critiques ne l’ont pas signalée. Ils se sont beaucoup souciés de citer Góngora et le Baroque, sans comprendre que le baroquisme éventuel de Tigres en el jardín possède une coloration moderniste très nette, ainsi qu’une présence considérable du Français Paul Valéry. Quant à l’arrière-plan idéologique, on y observe déjà ma préférence pour les philosophes épicuriens, née de la lecture des quelques fragments conservés d’Épicure et des traces qu’il a laissées chez d’autres philosophes, par exemple Lucrèce, dont j’ai fait une véritable pâture de lectures et que j’ai utilisé comme source de poésie. Mais ces choses appartiennent au monde intérieur des livres.',
        7: 'F. : Dans le livre Ciudades de Provincia, vous dites avoir traversé un moment d’écriture dangereux, par crainte d’être enfermé dans des formes déterminées...',
        8: 'A. C. : Ce n’était pas de la peur. C’est que, dès que la critique appose une « étiquette », elle vous confine dans les limites extrêmement étroites de cette définition. Un livre de poésie s’ouvre sur de nombreux fronts. Même si l’on cherche à lui donner une ligne cohérente, tant dans l’expression que dans les thèmes, un même livre peut en réalité engendrer de multiples prolongements et de multiples directions. Ainsi, dans Tigres en el Jardín, la présence de la douleur est très faible.',
        10: 'F. : Le thème des archanges est évoqué...',
        11: 'F. : Oui, certes, mais le thème de la douleur est très peu présent et il est même traité avec un certain dédain, parce qu’heureusement le poète se sent alors heureux. La situation change cependant beaucoup avec Serenata y Navaja, son deuxième livre, car la vie, que nous le voulions ou non, exerce son influence. Les processus vitaux agissent toujours sur les évolutions poétiques, et ma vie connut une série de bouleversements durant les années qui séparèrent Tigres en el Jardín de Serenata y Navaja. Je ne parle pas de leur publication, mais de la relation entre les livres : une série d’événements familiaux et d’une autre nature modifia la situation provisoire et relativement heureuse dans laquelle je vivais lorsque j’écrivis Tigres en el Jardín, et qui se défit lorsque j’écrivis Serenata y Navaja. La crainte d’être catalogué, je l’ai ressentie dans les critiques de Tigres en el Jardín : elles ne retenaient que les éléments formels. La critique n’a cessé de le répéter, et je suis toujours frappé que l’on ne parle que de ces éléments formels.',
        12: 'F. : Rechercher de nouvelles formes ?',
        13: 'A. C. : Non. Mon travail ne consiste pas tant à rechercher de nouvelles formes qu’à détruire et recomposer celles du passé. Je n’ai pas vraiment inventé ou « réutilisé » de combinaisons strophiques ; en revanche, j’ai détruit les formes anciennes pour tenter de leur donner un air nouveau, ce que je crois parvenir à faire dans Serenata y Navaja. On ne peut pas me classer parmi les novísimos, parce que la préoccupation politique et sociale demeure en moi ; on ne peut pas m’y inclure parce que mon sens de l’éthique est différent ; et on ne peut pas m’y inclure parce que j’ai toujours répété une phrase, de Ravelli je crois : « Science sans conscience est la ruine de l’âme ». Je l’ai toujours gardée à l’esprit comme une devise et, de mon premier livre au dernier, elle m’a conditionné et obligé à pratiquer un certain type de littérature. Oui, je crois à l’engagement de l’écrivain, et ce serait là le fait essentiel qui me sépare des novísimos.',
        14: 'F. : Dans votre livre Servidumbre de Paso, vous parlez de Pedro Soto de Rojas...',
        15: 'A. C. : Lorsque je parle de Pedro Soto de Rojas, je fais référence au poète, auteur de Desengaño de amor en rimas et de El paraíso cerrado para muchos, un jardín abierto para pocos. Je parle d’un poète auquel d’autres auteurs, comme Lorca ou Gerardo Diego, et même Neruda, accordèrent une très grande attention. S’il existe dans la poésie classique une référence que l’on puisse citer comme exemple de ce qui est grenadin, ce serait précisément lui : le premier à élaborer cette topique et à construire cette phrase comme titre de son livre, Paraíso cerrado para muchos, jardines abiertos para pocos, formule qui, à partir de Lorca, allait devenir un cliché pour désigner Grenade.',
        16: 'F. : Au début, j’avais même pensé à un lien avec Pedro Soto, théologien et philosophe espagnol des environs de 1500, qui parla de la doctrine du sacrement de l’Eucharistie...',
        17: 'A. C. : (Rires.) Cela ne serait pas non plus très surprenant, car Serenata y Navaja contient un poème intitulé Sobre el ardor de la lucha postrera, traduction d’un épigraphe de saint Thomas d’Aquin tiré d’une partie de sa Somme théologique. J’ai moi aussi lu un peu de théologie, surtout de théologie morale. L’un des livres que j’ai le plus consultés, précisément pour ne pas commettre d’erreurs amoureuses dans ma poésie, fut la Teología Moral du père Cullera.',
        19: 'F. : Dans Ciudades de Provincia, vous parcourez des villes comme Úbeda et Baeza et utilisez les symboles de la Nature pour décrire la beauté. Une phrase s’affirme : « L’Architecture comme bel art collectif... ». Au-delà du changement de formes, est-ce là le dessein de ce livre : décrire la beauté architecturale des villes de Jaén ?',
        20: 'A. C. : Plus précisément dans le poème Piedra viva (Amanecer en Úbeda), le premier consacré à un sujet de Jaén, qui se trouve dans Serenata y Navaja. Lorsque j’ai conçu ce livre, j’ai cherché à composer une série de poèmes sur les grands archétypes artistiques : pour la Musique, j’ai choisi Mozart ; pour la Sculpture, Bernardo Olmedo ; pour la Peinture, un tableau de Francisco Pedraja, Vista de Badajoz al atardecer ; et pour l’Architecture, je me suis appuyé sur Úbeda, concrètement sur l’espace urbain dominé par la chapelle d’El Salvador, cette façade avec son merveilleux arrière-plan lorquien d’oliveraies. C’est essentiellement tout l’espace de la place qui entre dans la vision du poème. Si l’on regarde attentivement Piedra Viva (Amanecer en Úbeda), on y trouve même un éloge du travail manuel collectif : il faut de nombreux tailleurs de pierre, maçons et carriers. Cela rompait précisément avec l’esthétique dominante de l’époque, où de tels sujets ne pouvaient être abordés parce qu’ils étaient jugés véritablement ordinaires. Lorsque les gens sont éblouis par l’éclat de Venise, par exemple, ils ne pensent pas à ceux qui l’ont bâtie. Ils voient le résultat, mais pas le processus ni le travail collectif qui a rendu possible cette merveille esthétique. Venise est un lieu merveilleux, mais Úbeda l’est aussi.',
        21: 'F. : Ce livre entretient-il un lien avec des amis qui vous sont chers ?',
        22: 'A. C. : Oui, ma poésie est généralement très motivée. Une partie de ce qu’elle raconte ne relève pas d’une anecdote ni d’une expérience que j’aurais vécue, mais fondamentalement de quelque chose que j’ai contemplé. Je prends habituellement beaucoup de distance avec les sujets que je traite, notamment parce qu’une émotion intense me permet seulement de la ressentir : sans distance, je ne peux pas écrire le poème. Je le dis dans De un Capricho a Celeste, plus précisément dans Confidencias de un hijo de este tiempo a Rafael León : j’ai besoin d’être calme et conscient pour accomplir la tâche d’écrire le poème, et même d’être proche du bonheur ; pas entièrement heureux, car lorsque je suis heureux, je n’écris pas.',
        23: 'F. : Seriez-vous alors comme un spectateur ?',
        24: 'A. C. : Non. La vie des autres n’est pas seulement une source d’inspiration pour le romancier. Le poète peut trouver des archétypes dans ce que les autres vivent, font et endurent. Il m’est assurément beaucoup plus facile de comprendre poétiquement ce qui arrive aux autres que de décrire les misères quotidiennes qui traversent mon for intérieur. J’ai la chance de pouvoir me prévaloir d’amis d’une immense qualité humaine, et cette qualité constitue peut-être la source principale de ma poésie.',
        25: 'F. : Antonio Carvajal est-il, d’une certaine manière, un paradis clos ?',
        26: 'A. C. : Non. Les relations d’amitié et d’amour impliquent normalement au moins deux personnes, et tous mes amis sont partagés ; ils ne sont ni exclusifs, ni uniques, ni enfermés. C’est un monde très ouvert. Il n’y a pas de clôture : l’intimité est une chose, le monde fermé en est une autre. Lorsque je rencontre quelqu’un qui commence à m’intéresser, je lui fais toujours passer un test pour savoir si je peux devenir son ami : je lui demande ce qu’il préfère, une Tour ou un Pont.',
        27: 'F. : Vous nous laissez dans le doute et la réflexion...',
        28: 'A. C. : Tous les sujets me touchent et ont affleuré dans ma poésie. Siesta en el Mirador, mon quatrième livre, reprend le titre d’un poème de mon premier ouvrage, Tigres en el Jardín. On y trouve une interprétation du mythe de Narcisse différente de la lecture conventionnelle. J’ai souvent dit que le narcissisme n’est pas quelque chose de nouveau : c’est une maladie très clairement décrite par les psychologues. Il existe un élément étrange : à la naissance de Narcisse, sa mère l’emmène chez le devin Tirésias. Lorsqu’elle lui demande : « Sera-t-il heureux ? », le devin répond : « Oui, s’il ne se connaît pas ». Fixer ainsi un destin, alors que l’oracle de Delphes affirme exactement le contraire — « Connais-toi toi-même » —, doit nous faire soupçonner quelque chose d’étrange dans le mythe. Narcisse meurt effectivement lorsqu’il se connaît, car le Narcisse du mythe ne tombe pas amoureux de lui-même : il s’éprend d’une créature d’une très grande beauté qu’il aperçoit, et c’est au moment où il découvre que cette créature est lui-même qu’il meurt. Cette interprétation est donc très singulière, et c’est précisément là que je place le poème Siesta en el Mirador — nous savons que le mirador est un balcon fermé. Narcisse n’aimait pas sa voix, mais son écho ; il ne s’aimait pas lui-même, mais l’image dont il ignorait qu’elle était la sienne.',
        29: 'F. : Vous êtes un observateur très sensible de tout ce qui vous entoure ; vous seriez comme un balcon ouvert, par lequel vous voyez entrer tous ceux qui sont autour de vous. Cette émotion se ressent précisément à la lecture de Noviembre, dédié à votre père, ainsi que dans le quinzième poème de l’Antología de Treinta años de Poesía Española, où vous semblez parler de votre fils : « ...Alguna vez mis labios, hijo mío,/ han buscado tu rostro... ».',
        30: 'A. C. : Ce n’est pas une expérience personnelle, car je suis heureusement célibataire et ne suis pas père célibataire. Il s’agit de la perte du père et du refus du fils, mais cette expérience, je le répète, n’a pas été vécue par moi. Je me suis appuyé sur la réaction d’un de mes amis face au refus de son fils. C’est un procédé sur lequel j’insiste. Dans Raso, Milena y Perla, par exemple, le poème dédié à Guillermo González fait intervenir tantôt Antonio Callejas, tantôt moi-même ; le poème se compose progressivement de tout ce que j’assimile de cette conversation.',
        31: 'F. : J’ai pu observer que Raso, Milena y Perla propose une description poétique d’amis et de personnes. Que pouvez-vous nous en dire ?',
        32: 'A. C. : Ce livre est entièrement motivé de l’extérieur. Il se construit en même temps que les derniers poèmes de Testimonio de Invierno, ceux de Miradas sobre el agua et ceux du dernier livre que j’ai achevé et remis à l’éditeur. C’est un ouvrage issu d’un processus de plusieurs années et de réponses à des peintres, sculpteurs et musiciens qui me demandent une collaboration pour des catalogues ou des œuvres. Je n’ai évidemment pas réuni tout ce que j’ai écrit pour les différents artistes : le livre cherche à rester cohérent. Dans certains cas précis, par exemple Fábula pagana et Fábula bíblica, mon écriture manuscrite prend appui sur des dessins de M. Teresa Martín Vivaldi, dédiés aux deux personnes auxquelles les tableaux furent ensuite offerts. Contrairement aux recueils de poésie qui constituent le reste de mon œuvre, Raso, Milena y Perla est entièrement motivé par l’amitié.',
        33: 'F. : Le message du livre pourrait-il donc être l’amitié elle-même ?',
        34: 'A. C. : Fondamentalement. Je crois qu’il contient une réflexion sur notre manière d’être au Monde et une réflexion sur l’Art, envisagé dans ses dimensions les plus générales comme les plus concrètes. J’y affirme que le tableau et le poème dureront plus longtemps que ceux qui les peignent ou les écrivent, et il y a une joie à savoir que l’œuvre survit à notre propre existence. Le livre contient bien d’autres choses, par exemple une interrogation sur le Bonheur. Dans le poème dédié à Asunción Jódar, qui constitue selon moi l’une des clés de toute ma poésie, on lit : « ¿Por qué los dioses fueron incapaces/ de hacer felices a sus hijos, todos;/ los padres deben ser crueles y mudos? ». J’insiste sur le mutisme du père, que l’on entendra ensuite à travers la paraphrase des sept paroles du Christ en croix et toute cette série d’éléments. Nous parlons du silence de Dieu.',
        35: 'F. : Et des Poemas de Granada...',
        36: 'A. C. : La paraphrase fut d’abord inscrite dans Poemas de Granada, mais sa place réelle, la place naturelle de cet ensemble de poèmes, se trouve dans Miradas sobre el agua.',
        37: 'F. : La Nostalgie cherche-t-elle Antonio au coin des rues ?',
        38: 'A. C. : Pas moi.',
        39: 'F. : Comment vous définiriez-vous ?',
        40: 'A. C. : Des mots comme « Névralgie » ou « Nostalgie » me font penser à des maladies que l’on soigne habituellement avec une aspirine ou quelque chose de ce genre. J’ai bien des accès de mélancolie, mais pas de nostalgie. Cela tient à ma manière de vivre. Je ne sais même pas si j’ai jamais employé ce mot dans un vers, je ne m’en souviens pas ; en revanche, j’ai utilisé le mot Mélancolie.',
        41: 'F. : Avez-vous une source cachée de mauvaise vie ?',
        42: 'A. C. : (Rires.) Naturellement !',
        43: 'F. : Comme tout bon artiste...',
        44: 'A. C. : Pas comme tout bon artiste, mais comme tout être humain qui veut vivre ! Nous serions bien avancés s’il fallait exposer notre intimité comme une vitrine de marchandises que l’on achète et que l’on vend !',
        45: 'F. : Êtes-vous satisfait de votre poésie ?',
        46: 'A. C. : Pas encore ; de certains poèmes, oui.',
        47: 'F. : Mais un écrivain n’atteint jamais la pleine satisfaction.',
        48: 'A. C. : Cela dépend de ceux auxquels je me compare. Si je me compare à la majorité des vivants, je suis presque pris d’accès de vanité et je finis presque par croire que je suis bon. Si je me compare à quelques vivants et à beaucoup de morts, l’humilité s’impose évidemment et il faut reconnaître que, selon ce que j’aime et ce que j’admets, il reste encore beaucoup de chemin avant d’atteindre cet échelon.',
        49: 'F. : Parlons-nous des anthologies ?',
        50: 'A. C. : Je dis toujours la même chose à propos des anthologies : il faut interroger les anthologistes et les lecteurs. Comment pourrais-je répondre à la place d’un anthologiste, de ses critères ou de ses goûts ? L’anthologie qui m’intéresse est celle dont je sais qu’elle a eu de véritables lecteurs et qui me permet de savoir quels poèmes ont atteint un groupe déterminé. Je veux connaître la réaction de mes lecteurs et, au moins, les anthologistes me garantissent qu’ils m’ont lu ; parfois, nos préférences coïncident. Dès l’instant où ils me choisissent, ils portent déjà un jugement sur moi. Les étiquettes qu’ils ajoutent relèvent ensuite de leur responsabilité. Je me contente de les remercier.',
        51: 'F. : Dormez-vous bien, ou les rêves vous réveillent-ils souvent ?',
        52: 'A. C. : Les rêves ne m’ont jamais réveillé ; les rêves... ne sont que des rêves.',
        53: 'F. : Les mêmes choses qu’il y a vingt ans continuent-elles de vous inspirer ?',
        54: 'A. C. : Bien davantage ! Heureusement, avec l’âge, le monde s’élargit beaucoup. Il se réduit aussi, car on se désintéresse de choses qui paraissaient fondamentales à dix-sept ans et dont on découvre ensuite qu’elles n’étaient que les fantaisies d’hier. Je partage tout à fait une déclaration de Carlos Fuentes, qui disait avoir été à vingt ans un parfait imbécile. Pour ma part, je situe mon degré d’imbécillité parfaite entre quinze et vingt-deux ans. À mesure que la vie vous corrige et vous remet à votre place, vous comprenez que les caprices d’enfant ne sont ni féconds ni capables de conduire quelque part. Je me souviens de cette peur de ne pas savoir que faire de ma vie, de cette sensation de vertige que donne le temps : ce fut pour moi la meilleure période physique et la pire période spirituelle. Rien n’est plus idiot qu’un adolescent ; j’ai été un adolescent très complet et donc parfaitement idiot.',
        55: 'F. : Il est très facile de regarder la vie à partir de l’expérience de l’avoir vécue...',
        56: 'A. C. : C’est que l’on nous appelle la beauté des fantômes. De même qu’un enfant de neuf ans choisit des marques de chemises, à dix-sept ans nous choisissons des marques de vie sans comprendre que la Vie doit se construire en commun avec les autres, avec le plus de générosité possible et le moins d’égoïsme possible. Il faut prendre conscience qu’il existe des formes de vie beaucoup plus authentiques, capables de se passer de tout ce qui nous accable, depuis ces divinités absolument hostiles jusqu’à ce commerce pressant qui fait de nous ses propres victimes : la Consommation.',
        57: 'F. : Une manière de vivre qui ne conduise pas à ces choses.',
        58: 'A. C. : Par exemple, s’accepter tel que l’on est. Il ne me viendrait pas à l’esprit d’envier l’homme qui passe dans la rue au volant d’une Jaguar — une voiture qui me plaît beaucoup, par ailleurs. Il serait bien plus beau de se promener sur le dos d’un véritable jaguar apprivoisé et de parcourir la Terre sur ce magnifique animal. Certains moments de bonheur suprême ont consisté à partager un vin dépourvu de toute marque.',
        59: 'F. : Cela se traduit-il dans la poésie que vous écrivez ?',
        60: 'A. C. : Je l’espère, même si l’on conserve ensuite ses insatisfactions spirituelles. Comme j’aimerais être heureux et ne pas écrire de poèmes ! Si j’étais absolument heureux, je n’écrirais pas ; je me consacrerais au bonheur, ce qu’il y a de plus égoïste et de plus beau.',
        61: 'F. : Je ne comprends pas ; le Bonheur peut résider dans l’écriture...',
        62: 'A. C. : J’en doute. Machado disait : Se canta lo que se pierde...',
        63: 'F. : Ou aussi ce que l’on gagne...',
        64: 'A. C. : Difficilement. Ce qui se passe, c’est que l’on voudrait saisir cet instant et que l’on écrit sur ce moment de bonheur pour qu’il perdure, revienne s’installer dans l’âme et ne disparaisse pas entièrement. Le poème a un sens comme jouissance esthétique et comme consolation. La fonction d’entremetteuse de la poésie m’a toujours enthousiasmé. Un poète véritablement entremetteur est l’un des instruments les plus nécessaires au développement de la vie humaine. Rien n’est plus merveilleux que de surprendre des adolescents s’échangeant des vers de Bécquer ou de Salinas, ou qu’un ami vienne un jour vous remercier parce qu’il a emprunté deux de vos vers pour faire une conquête. Cela me remplit de satisfaction, car je comprends avoir ainsi facilité la vie d’autrui. De même, lorsque je ne sais pas définir ce que je porte en moi, j’aime rencontrer le vers d’un autre, de Miguel Hernández par exemple, et pouvoir préciser mon état d’âme. Je peux définir mon adolescence par ces vers de Lorca : « ...Hoy tengo en el corazón un vago temblor de estrellas, y tengo las cosas son tan blancas como mi pena... ». Dans un moment de véritable malheur, je peux aussi me souvenir de ce vers de Miguel Hernández, « Cuánto penar para morirse uno », et continuer d’avancer... J’aime les poètes qui m’accompagnent. Une phrase de saint Augustin dit : « ...Belleza tan antigua y sin embargo nueva » — le mot « afín » me vient à l’esprit, puisque nous créons les dieux à notre image et à notre ressemblance. Cette phrase de saint Augustin nous invite à regarder autour de nous et à voir toute la beauté qui nous échappe, car la Beauté est toujours ancienne et toujours nouvelle, toujours passée et toujours présente.',
        65: 'F. : Le moindre détail peut renfermer davantage de beauté que tout un monde...',
        66: 'A. C. : Ce ne sont pas des grandeurs mesurables.',
        67: 'F. : Pensez-vous que l’on puisse distinguer un poète authentique de celui qui ne l’est pas ?',
        68: 'A. C. : Il existe un signe qui trompe rarement : le poète authentique, même dans ce qui paraît le plus vide ou le plus esthétisant, possède toujours un battement affectif qui se transmet, et cela se détecte facilement. Lorsqu’un esprit humain entre en contact avec le produit d’un autre esprit humain, ce phénomène se manifeste : une sorte de petit bouleversement nous avertit que la poésie véritable se trouve là. Si la poésie est authentique, le poème est bon. Il existe aussi des poètes très artificieux et éblouissants qui ne transmettent pas cette émotion ; le poème traverse alors notre esprit sans le briser ni le marquer, comme s’il n’avait jamais existé. Cela se ressent : les vrais poètes se reconnaissent toujours.',
        69: 'F. : Et le Prix national, Antonio, pour quand ?',
        70: 'A. C. : C’est le problème des jurys. Pour les prix, je dis la même chose que pour les anthologies : ce n’est ni la personne retenue ni le lauréat qu’il faut interroger, mais les anthologistes et les jurys, qui doivent répondre de leurs actes.',
        71: 'F. : Mais Antonio Carvajal n’en a pas besoin...',
        72: 'A. C. : (Rires.) À vrai dire, cinq millions de pesetas ne me feraient pas de mal !...',
        73: 'F. : Je ne faisais pas précisément référence à la question économique... Antonio Carvajal n’a plus besoin de ce prix.',
        74: 'A. C. : Les marques de reconnaissance d’autrui sont toujours bienvenues. On a beau prétendre se suffire à soi-même, si la récompense arrive, qu’elle soit bénie ! Ce que je ne peux pas faire, c’est m’abaisser à la mendier. S’ils ne me la donnent pas, ils auront leurs raisons ; qu’ils ne viennent pas me les demander ! (Rires.) Je ne souffre pas de ne pas la recevoir, et je ne vais pas non plus me réjouir excessivement si on me l’accorde.',
        75: 'F. : C’est précisément ce que je voulais dire...',
        76: 'A. C. : Je ne me souviens même pas de celui qui a reçu le prix il y a cinq, six ou sept ans. Les prix sont absolument éphémères. En revanche, si vous m’interrogez sur le Premio de las Letras Españolas, je m’en souviens, parce que le ministère de la Culture réalise de merveilleuses publications. Lorsqu’on les feuillette ensuite, on comprend qu’il s’agit d’un prix véritablement consistant, non seulement par sa dotation financière, mais aussi par la publication d’une série d’œuvres qui justifie une récompense de cette catégorie.',
        78: 'Antonio Carvajal, au nom de tous les lecteurs, nous souhaitons vous remercier ici de votre collaboration et de ces moments partagés de réflexion et de dialogue. Comme l’a dit Rubén Darío :',
    },
    'entrevista-juan-carlos-sunen': {
        10: 'Onze heures du matin. Nous sommes au Círculo de Bellas Artes de Madrid, où Juan Carlos Suñén, auteur de nombreux livres et lauréat de tout autant de prix nationaux, me reçoit.',
        13: 'F. : Vous publiez votre premier livre, PARA NUNCA SER VISTOS, en 1988. Quel est le propos de cette première publication ?',
        14: '— J’écrivais depuis longtemps et PARA NUNCA SER VISTOS est le premier livre que j’ai senti pouvoir publier. À ce moment-là, il m’importait beaucoup de ne pas faire ce qui se faisait dans le pays ; je n’aimais ni le vénétianisme ni la poésie réaliste qui commençait à s’affirmer avec la Poesía de la Experiencia. Je cherchais autre chose, je le cherchais chez mes classiques, de saint Jean de la Croix à Paul Celan ; PARA NUNCA SER VISTOS est un livre plus essentialiste que les précédents, dans lequel je suis probablement un écrivain encore incertain et où mon approche est plus intellectuelle qu’elle ne l’est aujourd’hui.',
        15: 'F. : Vous écriviez auparavant d’autres choses...',
        16: '— Oui, j’écrivais toutes ces choses que nous écrivons lorsque nous sommes plus jeunes, mais elles ne finissaient pas de me convaincre. Quand on est jeune, on tend à avoir des obsessions d’ordre intellectuel ; elles deviennent ensuite des obsessions réelles, ce dont je parlerais déjà dans les derniers livres, où j’aborde le temps, ma conception de la poésie, mes désirs à propos de la Vie ; des idées et des perceptions qui me préoccupent davantage intellectuellement qu’expérimentalement.',
        18: 'F. : Dans le livre suivant, UN ÁNGEL MENOS, les conditions de la vie et l’Être de la Vie se rejoignent davantage ; on y trouve des concepts bibliques. Pourquoi ce passage par des tonalités prophétiques pour parler de la Vie ?',
        19: '— Le langage prophétique m’intéressait parce qu’il m’obligeait à trouver des choses différentes, mais surtout parce que, même si je crois ne pas en avoir eu encore conscience, je commençais déjà à écrire avec ce qui serait mon écriture propre, qui au fond est ma vie elle-même. À ce moment-là, je crois que j’avais au moins une direction et quelques idées claires sur la Vie, ces silences énumérés dans le livre, où se rassemble tout ce à quoi la Vie ne répond pas, tout ce que chacun doit se répondre seul. C’est un livre de départ, d’initiation à la vie, pour le dire d’une façon peu heureuse mais exacte.',
        20: 'F. : Vous appuyez-vous sur un écrivain antérieur pour ces silences ?',
        21: '— Non, il n’y a aucun lien avec la Poesía del Silencio. Ce n’est pas un silence adopté sous l’influence de la littérature, c’est le silence du langage, un silence qui se produit parce que le langage lui-même est incapable de définir certaines choses ; c’est précisément là que surgit la Poésie, lorsque les mots doivent révéler ces silences et montrer au lecteur où ils se trouvent.',
        22: 'F. : En 1991 paraît POR FORTUNAS PEORES. L’auteur y décrit-il une expérience personnelle, avec les deux livres précédents qui forment une trilogie ?',
        23: '— Oui, ma vie est là aussi. Il y a peut-être davantage de réalité, en ce sens qu’il y a plus de passé que dans les autres livres, un passé plus assimilé, plus fataliste, même si le livre demeure optimiste. C’est un livre dans lequel je commence à demander des comptes au monde ; je ne lui dis pas seulement ce qui est à moi, je l’interroge aussi sur ce qui est à lui. Je commence également à penser davantage au lecteur comme à celui qui complète ou achève le poème. Je m’intéresse plus au mélange des genres littéraires, ou plutôt à la possibilité de ne me limiter à aucun genre : on entre et sort de la prose, on entre et sort de la poésie, je crois sans trop de difficultés, sans que l’on remarque que ce passage s’opère. Cela m’intéressait formellement et continue de m’intéresser aujourd’hui.',
        25: '[SUBTITLE-CENTER]Juan Carlos Suñén, Madrid, 1997',
        27: 'F. : Vous me dites que le lecteur est celui qui achève le poème. Est-ce peut-être un trait de la Poesía de la Experiencia ? Existe-t-il un lien avec votre œuvre ?',
        28: '— Je dois m’inscrire en faux contre cette idée : dans la Poesía de la Experiencia, le lecteur n’achève rien. Il reçoit un bloc de sens unidirectionnel dont il ne peut garder, après avoir lu le poème, qu’un petit résumé. Cela tient précisément à la définition que la Poesía de la Experiencia donne d’elle-même : une prose qui aurait fait de la gymnastique. Elle semble ne pas accepter d’essence propre ; selon ses poètes, la poésie serait un voile ou un embellissement de la prose. Je crois qu’elle élimine la part d’ambiguïté que doit avoir la poésie, le fait que le mot s’emploie avec beaucoup plus de valeurs que sa seule valeur conceptuelle, et le langage avec bien plus de sens qu’un simple sens syntaxique habituel. C’est là, selon moi, que commence la poésie ; mais c’est là qu’elle s’achève du point de vue de la Poesía de la Experiencia. Quand on laisse le poème ouvert, l’intervention du lecteur devient plus importante.',
        29: 'F. : À propos de LA PRISA, paru chez Cátedra en 1994, on a dit qu’il constituait l’une des expériences les plus riches de la poésie espagnole récente, où se rejoignent les voies de la lecture, la recherche sur le langage et l’analyse de la réalité. Comment J. C. Suñén analyse-t-il la Réalité dans ce livre ? Marque-t-il une rupture avec les précédents ?',
        30: '— Il apparaît comme une synthèse des différentes directions dans lesquelles j’avais cherché, avec la même obsession de rendre compte de la Vie. Dans ce livre, je me propose de parler de ma génération, ou mieux encore de la frustration de ma génération, qui eut l’horizon à portée de main et à qui il fut arraché ; je parle au sens politique. Mais au moment même de commencer à écrire un poème de façon consciente, c’est au fond l’expérience de tout être humain, à n’importe quel moment de sa vie, quelle que soit l’époque qui lui échoit. C’est un livre où la Réalité entre sous la forme du langage quotidien et où, derrière les scènes ordinaires, surgit le sens transcendant que je souhaite transmettre au lecteur : cette sensation de solidarité ou de consolation que l’on éprouve en lisant certains auteurs.',
        33: '[SUBTITLE-CENTER]Juan Carlos Suñén et Belén Juárez au',
        34: '[SUBTITLE-CENTER]Círculo de Bellas Artes de Madrid. 1997',
        37: 'F. : Y a-t-il un jeu avec le Temps ?',
        38: '— Il y a toujours un jeu avec le Temps, parce que nous sommes le passé ; lorsque nous pensons à notre propre vie, nous pensons au passé. La Vie se déroule dans le passé, mais nous ne le voyons pas toujours de la même façon : selon notre propre évolution, nous organisons le passé de manières différentes ; c’est le cœur qui organise notre passé, non la mémoire.',
        39: 'F. : Y a-t-il dans ce livre une histoire du langage ?',
        40: '— Moins que dans le précédent. Il y a une histoire du langage surtout dans certaines scènes du premier livre, PARA NUNCA SER VISTOS, où l’on parvient à éluder, de manière très voilée, ce qui était alors les exercices de langage ; mais cela est là. Et dans POR FORTUNAS PEORES, il existe un croisement constant entre la figure féminine et le langage : parfois, on ne sait pas exactement de quoi il est question. En tout cas, j’ai toujours eu le sentiment que rien de ce qui nous arrive ne nous arrive si cela ne passe pas par le langage. Le langage est la mesure du Réel.',
        50: 'F. : J. C. Suñén porte-t-il son regard en arrière dans le temps avec EL HOMBRO IZQUIERDO ?',
        51: '— Oui, du moins le protagoniste du livre, qui pourrait être le même personnage que celui qui, dans LA PRISA, conclut la dernière page en fermant la porte de sa maison et en y entrant. Ce même personnage pourrait analyser les mêmes choses, lui-même également, mais d’un autre point de vue. Il m’était difficile de me défaire du thème de LA PRISA ; je voulais écrire un livre qui ne soit pas LA PRISA-II et j’étais très conscient d’avoir besoin d’un lieu depuis lequel regarder la même chose. Ce lieu est apparu dans la Nature. C’est un livre où la Nature est très présente, où le discours est très proche du sol, mais cette Nature n’a pas de message particulier à donner à l’homme : c’est le sentiment d’un',
        52: 'personnage qui s’est perdu à un moment donné et qui se retrouve dans la Nature.',
        66: 'F. : Ce serait comme chercher le « Présent éternel »...',
        67: '— Je nomme le Présent éternel dans le premier livre ; c’est une idée de concepts, où l’Être et l’Être-là coïncident. Ce sont les instants que poursuit EL HOMBRO IZQUIERDO et qui organisent la succession du livre.',
        68: 'F. : Le silence existe-t-il dans vos vers ?',
        69: '— Oui, parfois davantage et parfois moins ; c’est comme la musique : on peut faire une pause et atteindre, par ce silence, l’auditeur ou la séquence suivante. Mais on peut aussi laisser quelques instruments résonner rythmiquement pour introduire ensuite, par une variation minime, l’épisode suivant. Je m’efforce de donner à mes poèmes une structure musicale et, en ce sens, le silence est indispensable.',
        70: 'F. : Le lecteur peut-il introduire sa propre vie dans ces livres ?',
        71: '— C’est l’intention. L’expérience qui pousse le poète à écrire est en même temps celle qu’il transmet au lecteur, mais il ne peut pas la lui transmettre en la lui disant : c’est ce que feraient, selon moi, les poètes de l’Expérience à travers un personnage interposé ou un autre, ou au moyen d’un corrélat objectif. Je pense qu’on ne peut pas la dire ; on peut en revanche placer le lecteur dans la situation de la vivre. Peut-être ne sera-t-elle pas exactement la même pour lui, mais ce n’est pas important ; ce qui importe, c’est qu’elle soit une expérience dans la même direction ou la même intuition que celle du poète au moment de l’écriture. En tout cas, l’essentiel est que le poème devienne expérience.',
        72: 'F. : « Un seul plaisir : l’Intelligence » (Guillermo Carnero). L’intelligence est-elle un plaisir pour J. C. Suñén ?',
        73: '— Elle l’est si elle ne fait pas mal. Si elle fait mal, c’est de la vanité. Cette phrase était citée par Clara Janés dans une critique de mon premier livre, et elle est juste parce que la poésie doit être cela : de l’intelligence, en tant qu’imagination au service de la vérité ; mais aussi du plaisir, en tant qu’incitation à marcher hors du chemin, autrement dit : de la séduction. Il ne s’agit pas, comme vous le voyez, d’être cultivé, bien que cela compte, mais de savoir douter, d’être critique.',
        74: 'F. : En 1991, comme critique littéraire à El País, trouvez-vous quelque difficulté à être à la fois poète et critique, c’est-à-dire à créer et à critiquer l’œuvre déjà créée ?',
        75: '— Non. Enfin, pas en dehors de la mesquinerie habituelle du milieu. Eliot disait que le poète qui pratique la critique court le risque de se laisser distraire par des problèmes qui ne troublent pas ses collègues moins inquiets. Je cite de mémoire, mais je me souviens d’une certaine ironie... Et je suppose bien sûr que nous parlons de critique écrite, car un poète qui ne serait pas critique est, me semble-t-il, inconcevable. En tout cas, on peut laisser le critique en position de rature pendant l’écriture du poème et attendre qu’il apparaisse une fois celui-ci écrit, pour qu’il lise sans passion et décide si ce qui est fait vaut quelque chose ou s’il faut poursuivre, et jusqu’où il doit laisser le poète le devancer. D’autre part, les critiques de poésie sont souvent eux-mêmes poètes. C’est une question de langage : comment parler d’un véritable poème sans posséder un langage capable de se mesurer à lui ? Et si l’on possède ce langage, comment y résister ? Voilà pourquoi les critiques tendent à privilégier le poème facile, celui dont ils peuvent parler.',
        77: 'F. : UN HOMBRE NO DEBE SER RECORDADO marque un changement radical par rapport aux trois premiers livres. Pourquoi la poésie comme conscience indomptable ?',
        78: '— C’est cela ou rien. Je ne peux pas écrire des poèmes en pensant à ce que l’on lit à l’université — un commerce qui se cache derrière une « poétique », soit dit en passant. Mais ce livre est en réalité un livret, comme un livret d’opéra ; il possède une volonté narrative et une progression dramatique pensées pour sa mise en scène. En l’écrivant, c’était le discours qui suivait le plan, non l’inverse. C’est pourquoi il demeure un livre solitaire parmi mes livres. Je ne le renie pas, ce n’est pas cela, mais c’est autre chose. En tout cas, oui, mon mépris pour certaines attitudes du pouvoir et du non-pouvoir y passait au premier plan...',
        92: 'F. : Dans PARA NUNCA SER VISTOS, vous décrivez le temps d’un âge, le temps d’un amour acheté, la reconstruction d’un temps passé et la conclusion du temps vécu. Est-ce du dépit de vivre dans un « présent éternel » ?',
        93: '— Du dépit ? Du malaise, peut-être, mais un malaise joyeux. Notre vie se déroule dans le passé et nos rêves dans l’avenir, mais la conscience est du présent, elle est présente, et le présent est le seul espace de liberté que je connaisse.',
        94: 'F. : La Mort, comme terme d’un temps, hante-t-elle PARA NUNCA SER VISTOS ?',
        95: '— Elle hante tous mes livres, mais non comme terme, plutôt comme un élément de ce présent. C’est la jeune mort, la mort moderne, qui n’est plus un point final, un lieu de l’avenir auquel ancrer la construction d’une vie, mais une présence actuelle que nous risquons de dévaloriser si nous ne nous préoccupons pas d’avoir une éthique du présent. Ce changement de statut de la mort rend caducs tous les arguments traditionnels et laisse la vie sans argument. Nous ne vivons plus pour la mort, mais avec elle ; cela ne me semble pas mauvais, je ne regrette pas l’autre état de choses. Vivre ainsi exige une autre responsabilité et une autre liberté, voilà tout ; et il n’est pas mauvais de se rappeler comment était le monde lorsqu’il avait un argument, parce que cet argument fut toujours au service d’une cause intéressée.',
        111: 'F. : Un ange vous guide-t-il lorsque vous prophétisez en vers ?',
        112: '— J’appelle « ange » tout ce qui dépasse notre capacité de compréhension, mais qui n’en demeure pas moins dans les choses. Mes anges sont matériels. Quant à mes prophéties, elles se font depuis la fatalité et concernent une première personne ; elles ne procèdent d’aucune foi. Ainsi, si un ange me guide, ce doit être l’ange de l’embrouillamini.',
        113: 'F. : Vos derniers travaux...',
        114: '— Je m’intéresse aux enfants ; je ne sais pas, je n’ai encore rien de clair. Je ne souhaite évidemment pas écrire « pour » les enfants, mais peut-être à leur sujet, bien que je n’aie encore rien à quoi me raccrocher... J’aimerais aussi achever un livre d’essais avec lequel je me bats depuis quelques années. Nous verrons bien.',
        145: '[SUBTITLE-CENTER]Illustration pour l’entretien',
        148: '[SUBTITLE-CENTER]Dédicaces de livres de J. C. Suñén à B. Juárez.',
    },
};

export const localizeInterview = (interview: Interview, locale: Locale): Interview => {
    if (locale !== 'fr') return interview;

    const translatedLines = FR_INTERVIEW_CONTENT[interview.slug];
    const content = translatedLines
        ? interview.content.split('\n').map((line, index) => translatedLines[index] ?? line).join('\n')
        : interview.content;

    return {
        ...interview,
        ...FR_INTERVIEW_METADATA[interview.slug],
        content,
    };
};
