import type { BookReview } from '../types';
import type { Locale } from './config';

export const REVIEW_UI: Record<Locale, {
    reviewOf: string;
    originalSource: string;
    readMore: string;
    back: string;
    literaryCriticism: string;
    share: string;
    print: string;
    coverAlt: (publication: string) => string;
    relatedImageAlt: (title: string) => string;
}> = {
    es: {
        reviewOf: 'Reseña de', originalSource: 'Ver fuente original', readMore: 'Seguir leyendo',
        back: 'Volver a reseñas', literaryCriticism: 'Crítica Literaria', share: 'Compartir', print: 'Imprimir',
        coverAlt: (publication) => `Portada de ${publication}`,
        relatedImageAlt: (title) => `Imagen relacionada con ${title}`,
    },
    fr: {
        reviewOf: 'Critique de', originalSource: 'Voir la source originale', readMore: 'Lire la suite',
        back: 'Retour aux critiques', literaryCriticism: 'Critique littéraire', share: 'Partager', print: 'Imprimer',
        coverAlt: (publication) => `Couverture de ${publication}`,
        relatedImageAlt: (title) => `Image associée à ${title}`,
    },
};

const FR_REVIEW_TRANSLATIONS: Record<string, Partial<BookReview>> = {
    'horizonte-de-sucesos-ideal-fernando-de-villena': {
        condensedQuote: 'Ce qui nous surprend d’abord dans ce livre, c’est sa nouveauté, son choix résolu d’une poésie quantique, dont Gregorio Morales fut un précurseur, ainsi que de l’intelligence artificielle ; ensuite, la vision positive de l’autrice : sa défense de la nature, des animaux, des arbres, de la pierre, de la mer, du cosmos tout entier ; un quasi-panthéisme et un ardent chant d’amour à la poésie…',
        fullContent: `Le silence que certains poètes gardent pendant de longues années, puis leur retour au moment où on les attend le moins, m’a toujours intrigué. Mais la poésie constitue un mystère absolu, et vouloir la soumettre aux normes de la normalité serait absurde.

La poète parisienne — professeure de microbiologie à l’Université de Grenade — Belén Juárez fut très active à la fin du siècle dernier et au début de celui-ci. Elle était alors liée à la revue « Ficciones » et à l’historique Tertulia del Salón, et publia les recueils « Destierro en Cuatro Ángulos » (1999) et « La Noche de Ayer » (2002). Des problèmes de santé l’éloignèrent ensuite de la vie littéraire. Elle revient récemment à la création par la grande porte avec un album musical, un spectacle audiovisuel et un nouveau livre de poèmes formant un ensemble intitulé « Horizonte de Sucesos » (Huerga y Fierro Editores, collection Rayo Azul, 2026). La présentation spectaculaire de ce projet s’est tenue au mois de mai à la Bibliothèque d’Andalousie.

Ce qui nous surprend d’abord dans ce livre, c’est sa nouveauté, son choix résolu d’une poésie quantique ; ensuite, la vision positive de l’autrice : sa défense de la nature, des animaux, des arbres, de la pierre, de la mer, du cosmos tout entier ; un quasi-panthéisme et un ardent chant d’amour à la poésie.

Des paysages et des animaux chargés de symbolisme nous sont présentés : la relecture du mythe des loups, ou encore le hibou, qui représente non seulement la sagesse de Minerve, mais aussi ce qu’il y a de plus intime, à l’image du phénomène poétique. Nous découvrons des images visionnaires, oniriques et audacieuses, ainsi que des références scientifiques dans des vers qui s’écoulent avec une force torrentielle, au rythme des parallélismes et des anaphores.

Ces poèmes sont imprégnés de couleur et déploient un lexique luxueux, extrêmement abondant — nival, bellido, dragontea, turpiales… — ainsi que de fréquentes comparaisons qui évoquent parfois Gerardo Diego : « Orcas como un manantial de espumas en alta mar ». Des vers auréolés de néoromantisme surprennent le lecteur : « Te esperaré como espera un amigo,/ dormido sobre el musgo de una tumba, en primavera ».

Face à toute cette célébration de la nature et de la poésie se dresse enfin un dur réquisitoire contre la ville, son asphalte, ses « afilados silbidos de neón » et sa tristesse.`,
        sourceLabel: 'Voir la critique dans IDEAL',
        detailImageCaption: 'Article publié dans IDEAL',
    },
    'belen-juarez-emocion-ciencia-en-benalmadena': {
        title: 'Belén Juárez surprend avec une nouvelle poésie qui associe émotion et science',
        condensedQuote: '… Cette publication est importante parce qu’elle réunit deux urgences de la culture actuelle : d’une part, retrouver des voix féminines au parcours pluriel ; d’autre part, expérimenter des formes qui dialoguent avec les savoirs scientifiques. À une époque où les frontières entre disciplines s’estompent, ce livre propose un modèle de coexistence entre précision et émotion…',
        fullContent: '… Cette publication est importante parce qu’elle réunit deux urgences de la culture actuelle : d’une part, retrouver des voix féminines au parcours pluriel ; d’autre part, expérimenter des formes qui dialoguent avec les savoirs scientifiques. À une époque où les frontières entre disciplines s’estompent, ce livre propose un modèle de coexistence entre précision et émotion…',
    },
    'horizonte-de-sucesos-cercle-artistes-europeens': {
        condensedQuote: '… Cet album constitue une création véritablement inédite : transformer sa poésie en chansons et les mettre en musique grâce à l’intelligence artificielle, afin d’ouvrir la poésie à un public plus large et de proposer une nouvelle voie d’accès à l’émotion poétique…',
        fullContent: '… Cet album constitue une création véritablement inédite : transformer sa poésie en chansons et les mettre en musique grâce à l’intelligence artificielle, afin d’ouvrir la poésie à un public plus large et de proposer une nouvelle voie d’accès à l’émotion poétique…',
    },
    'poesia-feria-libro-madrid-2026-librujula': {
        title: 'Poésie pour le Salon du livre de Madrid 2026',
        condensedQuote: 'Dans cet article, le critique et lecteur de poésie décrit la poésie de Belén Juárez comme « vérité et beauté dans des poèmes qui sont un cadeau pour notre cerveau ».',
        fullContent: 'Dans cet article, le critique et lecteur de poésie décrit la poésie de Belén Juárez comme « vérité et beauté dans des poèmes qui sont un cadeau pour notre cerveau ».',
    },
    'horizonte-de-sucesos-librujula': {
        condensedQuote: '… Le recueil aborde différents sujets : la nature, avec sa flore et sa faune terrestre — le loup, qui fait écho au frère loup de Gubbio et à François d’Assise —, aérienne — le hibou sage — et marine — la défense de l’orque, delphinidé —, entre autres thèmes. « Horizonte de Sucesos » nous montre également que poésie et science, ou science et poésie, sont très semblables : elles partagent et mettent en jeu l’intuition ainsi qu’une juste et nécessaire part de hasard, qui suppose un saut dans le vide de la foi, cette foi en soi-même et en son travail, dans la crainte et le tremblement.',
        fullContent: '… Le recueil aborde différents sujets : la nature, avec sa flore et sa faune terrestre — le loup, qui fait écho au frère loup de Gubbio et à François d’Assise —, aérienne — le hibou sage — et marine — la défense de l’orque, delphinidé —, entre autres thèmes. « Horizonte de Sucesos » nous montre également que poésie et science, ou science et poésie, sont très semblables : elles partagent et mettent en jeu l’intuition ainsi qu’une juste et nécessaire part de hasard, qui suppose un saut dans le vide de la foi, cette foi en soi-même et en son travail, dans la crainte et le tremblement.',
    },
    'horizonte-de-sucesos-en-clase-ideal': {
        title: 'Horizonte de Sucesos, un projet né après deux décennies de silence lyrique',
        condensedQuote: 'À propos de « Horizonte de Sucesos », elle explique que le projet naît « de cette recherche ou de cette idée de dialogue et de conversation entre le poète et la poésie. Le poète interroge ainsi son travail au sein de son écriture, tandis que la poésie l’entraîne sur différents chemins ». Le titre vient du dernier chapitre et désigne « un livre consacré à de nombreuses facettes de la vie ».',
        fullContent: 'À propos de « Horizonte de Sucesos », elle explique que le projet naît « de cette recherche ou de cette idée de dialogue et de conversation entre le poète et la poésie. Le poète interroge ainsi son travail au sein de son écriture, tandis que la poésie l’entraîne sur différents chemins ». Le titre vient du dernier chapitre et désigne « un livre consacré à de nombreuses facettes de la vie ».',
    },
    'la-noche-de-ayer-extramuros': {
        condensedQuote: '[...] La poète, peintre, traductrice, anthologiste, critique et chercheuse de l’Université de Grenade, Belén Juárez, surprend une nouvelle fois lecteurs avertis et profanes avec la publication de son deuxième recueil, *La Noche de Ayer*. Une poésie moderne, douée du sens du rythme et d’une oreille cultivée… une construction extérieure soignée et des mots délimités avec une grande précision. Ce recueil est véritablement une remarquable réussite, dont la lecture s’impose. [...]',
        fullContent: `Je crois que Francisco Morales Lomas a raison lorsqu’il affirme, dans *Poesía andaluza en libertad (una aproximación antológica a los poetas andaluces del último cuarto de siglo)* (Corona del Sur), à la page 45 de son étude introductive, que la poésie de la dernière décennie se caractérise par sa diversité : dédain pour la politique, préoccupation pour les questions sociales, lyrisme métaphysique ou abstrait, surréalisme, poésie rock, réalisme sale, néobaroque, mysticisme hétérodoxe et culturalisme ; en somme, les mêmes tendances que la poésie des années quatre-vingt avait déjà expérimentées, sans apports majeurs. Or voici que la poète, peintre, traductrice, anthologiste, critique et chercheuse de l’Université de Grenade Belén Juárez (Paris, 1965) surprend une nouvelle fois lecteurs avertis et profanes avec son deuxième recueil, *La Noche de Ayer* (Alhulia), après *Destierro en cuatro ángulos* (Devenir, 1999). Une heureuse surprise, comme le révèle la lecture. À la date de parution de l’anthologie citée, Morales Lomas ne connaissait probablement pas encore la poésie de Juárez. Celle-ci apporte pourtant de la nouveauté : moderne, elle possède le sens du rythme et une oreille cultivée, recourt généralement aux hendécasyllabes et aux alexandrins, et témoigne d’une parfaite connaissance du langage. La poète sait quelle conception précise exige chaque poème : construction extérieure soignée, termes rigoureusement délimités, disparition des espaces vides, de la rhétorique grandiloquente et du verbiage. Ce recueil est véritablement une remarquable réussite. *La Noche de Ayer* est une lecture indispensable.

Soigné dans sa forme comme dans son contenu, le recueil s’ouvre sur un juste propos liminaire du poète et critique grenadin Antonio Enrique, qui avertit d’emblée le lecteur de la structure singulière de la poésie de l’autrice.

*La Noche de Ayer* est un recueil solidement structuré, divisé en trois temps de dix poèmes chacun. Le livre est dédié au poète, au lecteur et à la poésie, car la poésie est écrite par le poète et le poète existe en elle comme dans le lecteur : « Al poeta allá donde exista, allá donde sea, del mundo, del tiempo…, su hogar ». Juárez nous donne ainsi des repères pour aborder cette nuit de la Saint-Jean, date significative de l’impression du livre et de la poésie espagnole universelle et sans frontières, de Jean de la Croix à J. R. J. et J. A. Valente. Le premier temps s’ouvre sur une citation de Manuel Mantero : « Éranos niños, pájaros de cuenta./ Éramos lo que sobre de la tormenta, / sexo escupido, edén falsificado/ y lamentabilísima osamenta / de un dios en estertor, crucificado ». Le deuxième est introduit par José Hierro : « Cuando la vida se detiene, / se escribe lo pasado o lo imposible / para que los demás vivan aquello / que ya vivió (o no vivió) el poeta ». Le troisième est placé sous le signe de Miguel Delibes : « Al hombre, por el mero hecho de vivir, / le era necesario aprender antes a desprenderse / de todo con una sonrisa de escepticismo. / -Vivir es ir pendiendo me decía… ». Le chemin de la poète et ce que nous trouverons dans sa nuit apparaissent clairement. Ces citations soigneusement choisies en témoignent, tout comme le poème en italique qui traverse le livre, du quatrième poème du premier temps jusqu’au dernier vers du trentième et ultime poème.

Belén Juárez écrit une poésie qui expose ses obsessions esthétiques et éthiques : de la maxime latine invitant à se hâter lentement à l’amour perdu et à l’éloignement de sa ville natale ; de l’émotion à l’existence, elle rappelle le paradis perdu de l’enfance, le monde de la nuit vécue hier, le verbe advenu et ses vers, dans des pages et des poèmes longuement médités et tissés : « Tres verbos ceden al vacío su figura » ; « el primero de los verbos define su buena intención / de conmover a los sensatos » ; « El segundo de los verbos recrea los deseos / y sigue perturbando a los sensatos » ; « Y, el tercero de los verbos comprende a los otros, / entender su poco uso cuesta un tono de justicia ».

J’y vois l’image du combat de Jacob avec son Dieu pour obtenir la bénédiction, image du combat spirituel, et celle de son rêve au pied de l’échelle pour atteindre la Lumière : l’image du poète dans sa lutte singulière avec la poésie, pour la rejoindre et recevoir sa bénédiction. « Hubo una noche, perla de perlas (…) / de paraísos perdidos… ». C’est un livre fermé et ferme, nullement le cahier d’essais d’une apprentie : l’autrice maîtrise ce travail de démiurge. « Porque todo desde las estrellas se susurra, / y viene la medida a establecer su noche ». Il ne s’agit en rien de simples notes. Belén Juárez sait qui elle est et agit en conséquence. Elle est poète. « Conservo la belleza de estos años, / a mitad de precio. Y guardo en mágicos lenguajes / el placer de haber sido en el lugar de las hadas, / servidor de fábulas narradas. (…) ». Elle connaît le chemin qu’elle doit parcourir dans et avec sa poésie : « Y por qué a consecuencia de tu amor / sigue este accidente de palabras… ».

Avec ses échos divers et pluriels, le livre réunit des poèmes de trois à vingt-deux vers, tous d’une grande intensité et traversés par la philosophie la plus profonde. Leur fil conducteur est la quête de la poésie — déjà perceptible à travers les verbes —, de la passion, du désir et de l’attirance pour certaines réalités qui habitent le recueil. « Holanda está lejos, y París y las estrellas ». Les trois temps forment un livre unitaire. C’est le meilleur livre que j’aie lu de la fin du siècle dernier ; il ouvre, pour le nouveau siècle, une porte ancrée dans la réalité poétique comme parole inventée : « Raro el momento de la lluvia que no moja ». Il ouvre cette porte à la poésie écrite par les femmes et les hommes, à toute la poésie du panorama mondial, pour autant que je le connaisse : « Sin embargo, queda la Poesía que consiguió crecer convirtiéndose en Dama a costa de la propia materia engendrada y desintegrada en los momentos, y éste, ciertamente, es el mayor de los honores a que puede aspirar El Poeta ».

Belén interroge toute chose et par tous les moyens : l’existence et la mystique de l’être humain, quels que soient son nom et sa religion. C’est une poète qui puise aux sources de la poésie arabo-andalouse. « Piensa, Amor, que la garganta aún procura / los versos de ayer, y esta luz / me iguala a tu recuerdo… ». Grenade, avec ses échos, ses lumières et ses ombres, retrouve ainsi une poète qui garde présente *La Noche de Ayer*, la nuit de la véritable poésie, non celle de l’anecdote maladroitement élevée au rang de poésie. Ceci est de la poésie ; le reste relève trop souvent de journalistes devenus critiques ou de critiques devenus journalistes. « Cierto es que el amor lo destruye todo, / a pesar de su buen nombre… ». Et Belén Juárez peut dire avec Baudelaire « Je sens vibrer en moi toutes les passions », ou avec ses propres mots : « Brillar entre los peces, advierte que el amor existe ».`,
    },
    'un-mandala-de-libro-turia': {
        title: 'Un livre-mandala',
        condensedQuote: '[...] Livre clos, originel, cyclique, silencieux, hors du temps. Tourné vers l’avenir. Initiatique. Prophétique par ce qu’il contient de divination et, simultanément, élégiaque par la profonde lamentation qui sous-tend sa belle et sévère impassibilité. Les quatre angles du temps, les quatre coins de l’univers assistant à leur propre destruction et à leur mort. [...]',
        fullContent: `L’ouvrage comporte quatre parties placées sous le signe des matières cosmiques — terre, eau, air et feu, dans cet ordre —, chacune accueillant douze poèmes toujours pourvus des mêmes titres et distribués selon un ordre analogue. Le livre tourne ainsi sur lui-même et se déplace en ellipse : il possède des axes de rotation, dans ses poèmes, et de translation, dans les parties qui les structurent. Mais autour de quelle idée, ou de quelles idées, oscille et se meut cet orbital et planétaire *Destierro en cuatro ángulos* ? Le temps et la désintégration de tout ce qui vit, la vanité des passions, la condition d’exil de l’être humain, la tentation de la violence et l’incapacité radicale à jouir comptent parmi ses thèmes récurrents. Les axes autour desquels tourne cette grande pomme du monde transfigurée en livre ne sont pourtant autres que le Néant et son masque — contingent, banal — dans la Vie. Nous sommes donc devant un texte initiatique : ce qui se voit et se lit est le symbole de l’invisible, sa forme transitoire. Il est rare de rencontrer un tel premier livre. Son autrice, Belén Juárez, est née à Paris en 1965 et vit à Grenade. Peintre et traductrice du français, remarquable et sélective, elle avance au rythme de l’esprit de cette culture, qui consiste à établir un ordre — esthétique, vital, mental — au sein de la dispersion et, en définitive, à articuler le visible dans le métaphysique.

Un tel livre — disons-le : mandalique, statique et cinétique à la fois — offre le kaléidoscope de deux lectures distinctes : diachronique ou verticale, de la première à la quatrième partie, et synchronique ou horizontale, chaque poème dans ses quatre temps. J’ose recommander cette dernière, plus éclairante. Elle permet de percevoir non seulement la gradation d’une même idée directrice à travers quatre tonalités différentes, mais aussi la sphéricité extérieure de l’œuvre, son unité d’ensemble et son extraordinaire densité. Chaque poème, inséré dans chacune des quatre sections, agit comme l’encoche qui assemble une roue à une autre et dont le mouvement entraîne les restantes, dans cette machinerie à la fois terrestre et céleste. Les mêmes syntagmes — « sandalias del pescador », « trono de la poca vergüenza », « morder los antebrazos », « cuerpos hermosos y no tan hermosos » — changent de position d’un poème à l’autre de même titre, selon un mouvement imperceptible mais réel, semblable à celui d’étoiles de magnitude comparable dans un ciel nocturne. Il existe donc un temps mental au sein d’un ordre chronologique : une préhistoire sismique correspondant au passage de la larve à l’homo erectus ; une ère des mythes antérieure à l’établissement de la Loi ; l’époque de la raison et de la conscience du passage du temps ; enfin une période terminale de dissolution du moi et d’abandon devant ce sphinx du Néant dissimulé par le hasard.

Le style est cryptique, la syntaxe abrupte, le ton rituel et la composition chorale ; la métaphore est absorbante, brillante, sèche, brusque, obsessionnelle. Elle n’est pas seulement la configuration du mythe essentiel et la fragmentation du symbole global de l’existence : elle devient la norme même du langage, l’unique voie permettant de dévoiler le sens caché de la vie. Cette conception de la métaphore possède ainsi quelque chose du « buisson ardent ». Elle exige son propre espace expressif : transitions rapides, omission des prédicats, fusion des première et troisième personnes, adjectivation réduite et adverbialisation minimale. Le langage se fait substantif, *se minéralise*. Tous ses éléments s’ordonnent et s’aimantent vers cette métaphore ancestrale, substitut du Néant, toujours en relation avec l’être : l’Exil. L’exil comme destin et comme nature. Nous sommes des dieux, nous l’avons été et nous le redeviendrons lorsque nous mourrons.

Livre clos, originel, cyclique, silencieux, hors du temps. Tourné vers l’avenir. Initiatique. Prophétique par ce qu’il contient de divination et, simultanément, élégiaque par la profonde lamentation qui sous-tend sa belle et sévère impassibilité. Il gravite, lévite, enveloppe, envahit et séquestre. Les quatre angles du temps, les quatre coins de l’univers assistant à leur propre destruction et à leur mort. Une entropie qui délimite leurs confins.`,
        date: 'Juin 2000',
    },
};

export const localizeBookReview = (review: BookReview, locale: Locale): BookReview =>
    locale === 'fr' ? { ...review, ...FR_REVIEW_TRANSLATIONS[review.id] } : review;
